/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-07-07 02:20:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.schedule;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.spring.model.*;

public final class chat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/triplanworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Triplan/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1463983535931L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.spring.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#gh_chatroom {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 85%;\r\n");
      out.write("\t\tborder-bottom: 1px solid gray;\r\n");
      out.write("\t\toverflow-y: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#gh_chatinput {\r\n");
      out.write("\t\tmargin: 4% 0 0 4%;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#chatMsg {\r\n");
      out.write("\t\tmargin: 0 2% 0 1%;\r\n");
      out.write("\t\twidth: 65%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.gh_date {\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tcolor: gray;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.gh_send {\r\n");
      out.write("\t\tpadding: 3px 5px 3px 5px;\r\n");
      out.write("\t\tbackground-color: pink;\r\n");
      out.write("\t\tborder-radius: 5px;\r\n");
      out.write("\t\tfloat: right;\r\n");
      out.write("\t\tmargin-right: 3%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.gh_sendTime {\r\n");
      out.write("\t\tcolor: gray;\r\n");
      out.write("\t\tfloat: right;\r\n");
      out.write("\t\tmargin-right: 3%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.gh_receiveTime {\r\n");
      out.write("\t\tcolor: gray;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tmargin-left: 3%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.gh_receive {\r\n");
      out.write("\t\tpadding: 3px 5px 3px 5px;\r\n");
      out.write("\t\tbackground-color: pink;\r\n");
      out.write("\t\tborder-radius: 5px;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tmargin-left: 3%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/jquery-2.0.0.js\" ></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" \r\n");
      out.write(" \tvar temp = 0;\r\n");
      out.write(" \tvar send = 0;\r\n");
      out.write(" \tvar bfchatcount = 0;\r\n");
      out.write(" \tvar chatcount = 0;\r\n");
      out.write(" \t\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tstartAjaxCalls();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#chatMsg\").focus(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(this).keydown(function(event){\r\n");
      out.write("\t\t\t\tif(event.keyCode == 13)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tif(send == 0)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tsendMsg();\r\n");
      out.write("\t\t\t\t\t\tsned = 1;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t}); // end of $(document).ready() -------------\r\n");
      out.write("\t\r\n");
      out.write("\tfunction startAjaxCalls() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgetChat();\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\tstartAjaxCalls();\r\n");
      out.write("\t\t} , 100); \r\n");
      out.write("\t\t\r\n");
      out.write("\t}// end of startAjaxCalls()----------------\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getChat()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t url: \"/triplan/callChatroom.tp\",\r\n");
      out.write("\t\t\t type: \"POST\",\r\n");
      out.write("\t\t\t data: \r\n");
      out.write("\t\t\t\t{ roomNo : $(\"#roomNo\").val() },  // 전송해야할 데이터\r\n");
      out.write("\t\t\t dataType: \"json\", \r\n");
      out.write("\t\t\t success: function(data) {\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\tvar html = \"\";\r\n");
      out.write("\t\t\t\tvar date = '';\r\n");
      out.write("\t\t\t\tvar time = '';\r\n");
      out.write("\t\t\t\tvar beforeDate = '';\r\n");
      out.write("\t\t\t\tvar msg = \"\";\r\n");
      out.write("\t\t\t\tchatcount = 0;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.each(data, function(entryIndex, entry){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tdate = entry.regDate.substring(0, 10);\r\n");
      out.write("\t\t\t\t\ttime = entry.regDate.substring(10, 16);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(date != beforeDate)\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\thtml += \"<div class='gh_date'>\" + date + \"</div><br/>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(entry.userid == \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\") // 보낸 메세지일 경우\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\thtml += \"<span class='gh_send'>\" + entry.chatMsg + \"</span> <br/>\";\r\n");
      out.write("\t\t\t\t\t\thtml += \"<div class='gh_sendTime'>\" + time + \"</div> <br/><br/>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\telse if(entry.userid != \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\") // 받은 메세지일 경우\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\thtml += \"<div class='gh_receiveId'>\" + entry.userid + \"&nbsp; </div>\";\r\n");
      out.write("\t\t\t\t\t\thtml += \"<div gh_sendMsg>\";\r\n");
      out.write("\t\t\t\t\t\thtml += \"<span class='gh_receive'>\" + entry.chatMsg + \"</span>\";\r\n");
      out.write("\t\t\t\t\t\thtml += \"<div class='gh_receiveTime'>\" + time + \"</div> <br/><br/>\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tbeforeDate = date;\r\n");
      out.write("\t\t\t\t\tchatcount++;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}); // end of each() -------------\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#gh_chatroom\").html(html);\r\n");
      out.write("\t\t\t\tif(bfchatcount != chatcount)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tbfchatcount = chatcount;\r\n");
      out.write("\t\t\t\t\t$(\"#gh_chatroom\").scrollTop(99999999999999);\r\n");
      out.write("\t\t\t\t}\t\t\t\t\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write(" </script>\r\n");
      out.write(" \r\n");
      out.write(" <script type=\"text/javascript\">\r\n");
      out.write(" \r\n");
      out.write(" var send_count = 0;\r\n");
      out.write(" \r\n");
      out.write("    function sendMsg()\r\n");
      out.write("    {\r\n");
      out.write("    \tif(send_count == 0)\r\n");
      out.write("    \t{\r\n");
      out.write("    \t\tsend_count = 1;\r\n");
      out.write("\t    \t$.ajax({\r\n");
      out.write("\t\t\t\t url: \"/triplan/sendMsg.tp\",\r\n");
      out.write("\t\t\t\t type: \"POST\",\r\n");
      out.write("\t\t\t\t data: \r\n");
      out.write("\t\t\t\t\t{ \r\n");
      out.write("\t\t\t\t\t\troomNo : $(\"#roomNo\").val(), \r\n");
      out.write("\t\t\t\t\t\tchatMsg : $(\"#chatMsg\").val()\r\n");
      out.write("\t\t\t\t\t},  \r\n");
      out.write("\t\t\t\t success: function(data) {\r\n");
      out.write("\t\t\t\t\t getChat();\r\n");
      out.write("\t\t\t\t\t $(\"#chatMsg\").val(\"\");\r\n");
      out.write("\t\t\t\t\t send_count = 0;\r\n");
      out.write("\t\t\t\t }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write(" \t<h1 style=\"text-align:center;\">*** 채팅 ***</h1>\r\n");
      out.write("\t<div id=\"gh_chatroom\"></div>\r\n");
      out.write("\t<div id=\"gh_chatinput\">\r\n");
      out.write("\t\t입력 : <input type=\"text\" id=\"chatMsg\" name=\"chatMsg\" />\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"roomNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sc_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn\" style=\"top:100%\" onClick=\"sendMsg();\">전송</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
