/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-07-07 02:23:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.schedule;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.spring.model.*;
import java.util.*;

public final class editSchedule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/triplanworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Triplan/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1463983535931L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.spring.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 MemberVO member = (MemberVO)session.getAttribute("member"); 
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<script src=\"http://maps.googleapis.com/maps/api/js?key=AIzaSyAfN2Bk4lSWLI3icy1x15wZXvLY0XpAims\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#screen{\r\n");
      out.write("\t\theight:auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#totalscreen {\r\n");
      out.write("\t\theight:auto;\r\n");
      out.write("\t\tpadding: 0 9% 0 15%;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("  #leftscreen {\r\n");
      out.write("  \t  width:35%;\r\n");
      out.write("  \t  height:auto;\r\n");
      out.write("  \t  float:left;\r\n");
      out.write("  \t  padding-left:10px;\r\n");
      out.write("  \t  padding-top:5%;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  #rightscreen {\r\n");
      out.write("  \t  width:60%;\r\n");
      out.write("  \t  height:auto;\r\n");
      out.write("  \t  float:left;\r\n");
      out.write("  \t  padding-left: 1%;\r\n");
      out.write("  \t  padding-right:10px;\r\n");
      out.write("  \t  padding-top:5%;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  #chatscreen {\r\n");
      out.write("  \tmargin: 52px 0 0 0;\r\n");
      out.write("  \tleft: 97.5%;\r\n");
      out.write("  \twidth: 2.5%;\r\n");
      out.write("  \theight: 89%;\r\n");
      out.write("  \tfloat: right;\r\n");
      out.write("  \tposition: fixed;\r\n");
      out.write("  \tborder: 1px solid #ddd;\r\n");
      out.write("  \tbackground-color :  #f2f2f2;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  #chatroom {\r\n");
      out.write("  \tdisplay: none;\r\n");
      out.write("  \theight: 100%;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  #googleMap {\r\n");
      out.write("      height:40%;\r\n");
      out.write("      width:100%;\r\n");
      out.write("      float:right;\r\n");
      out.write("  \t  padding-right:10px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  #edsc_search {\r\n");
      out.write("  \tpadding-left: 0%;\r\n");
      out.write("  \tfloat: left;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  #timeTable {\r\n");
      out.write("      height:auto;\r\n");
      out.write("      width:100%;\r\n");
      out.write("      float:left;\r\n");
      out.write("  \t  padding-left:10px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  #list {\r\n");
      out.write("      height:50%;\r\n");
      out.write("      width:100%;\r\n");
      out.write("      float:right;\r\n");
      out.write("  \t  padding-right:10px;\r\n");
      out.write("  \t  padding-top:10px;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  #list>ul>li>a {\r\n");
      out.write("  \tpadding : 7px 13px;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  #display_tlist {\r\n");
      out.write("  \tmin-height: 110%;\r\n");
      out.write("  \tmax-height: 110%;\r\n");
      out.write("  \toverflow-y: auto;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  #jh_table {  \r\n");
      out.write("  \ttext-align: center;\r\n");
      out.write("  \tfont-size: 92%;\r\n");
      out.write("  }\r\n");
      out.write(" \r\n");
      out.write("  .jh_sctime {\r\n");
      out.write("  \twidth: 10% !important;\t\r\n");
      out.write("  \tdisplay: table-cell !important;\r\n");
      out.write("  \ttable-layout: fixed;\r\n");
      out.write("  }\r\n");
      out.write(" \r\n");
      out.write(" #jh_table>thead>tr>td {\r\n");
      out.write(" \tpadding : 8px;\r\n");
      out.write(" \twidth: 30% ;\r\n");
      out.write(" \tdisplay : none;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" #jh_table>tbody>tr>td {\r\n");
      out.write(" \tpadding : 8px;\r\n");
      out.write(" \twidth: 30% ;\r\n");
      out.write(" \tdisplay : none;\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  .view {\r\n");
      out.write("  \tdisplay: table-cell !important;\r\n");
      out.write("  }\r\n");
      out.write(" \r\n");
      out.write(" .jh_btn_left, .jh_btn_right {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tcolor: blue;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write(" }\r\n");
      out.write("  \r\n");
      out.write(" .ti_on_sc1{\r\n");
      out.write(" \tborder: 1px solid #3399ff;\r\n");
      out.write(" \tbackground-color: #cce6ff;\r\n");
      out.write(" \tpadding : 0;\r\n");
      out.write(" \tfont-size: 10pt !important;\r\n");
      out.write(" }\r\n");
      out.write(" .ti_on_sc1 img{\r\n");
      out.write(" \tmargin-top: 2px;\r\n");
      out.write(" \tmargin-bottom: 2px;\r\n");
      out.write(" \theight: 24px !important;\r\n");
      out.write(" \twidth: 24px !important;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" .ti_on_sc2{\r\n");
      out.write(" \tborder: 1px solid #e6005c;\r\n");
      out.write(" \tbackground-color: #ffcce0;\r\n");
      out.write(" \tpadding : 0;\r\n");
      out.write(" \tfont-size: 10pt !important;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" .ti_on_sc2 img{\r\n");
      out.write(" \tmargin-top: 2px;\r\n");
      out.write(" \tmargin-bottom: 2px;\r\n");
      out.write(" \theight: 24px !important;\r\n");
      out.write(" \twidth: 24px !important;\r\n");
      out.write(" }\r\n");
      out.write(" .ti_on_sc3{\r\n");
      out.write(" \tborder: 1px solid #0033cc;\r\n");
      out.write(" \tbackground-color: #ccd9ff;\r\n");
      out.write(" \tpadding : 0;\r\n");
      out.write(" \tfont-size: 10pt !important;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" .ti_on_sc3 img{\r\n");
      out.write(" \tmargin-top: 2px;\r\n");
      out.write(" \tmargin-bottom: 2px;\r\n");
      out.write(" \theight: 24px !important;\r\n");
      out.write(" \twidth: 24px !important;\r\n");
      out.write(" }\r\n");
      out.write(" .ti_on_sc4{\r\n");
      out.write(" \tborder: 1px solid #ff5c33;\r\n");
      out.write(" \tbackground-color: #ffd6cc;\r\n");
      out.write(" \tpadding : 0;\r\n");
      out.write(" \tfont-size: 10pt !important;\r\n");
      out.write(" }\r\n");
      out.write("  \r\n");
      out.write(" .ti_on_sc4 img{\r\n");
      out.write(" \tmargin-top: 2px;\r\n");
      out.write(" \tmargin-bottom: 2px;\r\n");
      out.write(" \theight: 24px !important;\r\n");
      out.write(" \twidth: 24px !important;\r\n");
      out.write(" }\r\n");
      out.write("  \r\n");
      out.write(" .copy {\r\n");
      out.write(" \tborder: 1px solid #ddd;\r\n");
      out.write(" \tborder-top: none;\r\n");
      out.write(" \tfont-size: 12pt;\r\n");
      out.write(" }\r\n");
      out.write(" \r\n");
      out.write(" .gmselect {\r\n");
      out.write("     margin: 10px;\r\n");
      out.write("    z-index: 0;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    left: 0px;\r\n");
      out.write("    top: 0px;\r\n");
      out.write(" }\r\n");
      out.write("  \r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/jquery-2.0.0.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tvar sc_idx = ");
      out.print(request.getAttribute("sc_idx"));
      out.write(";\r\n");
      out.write("\r\n");
      out.write("\tvar webSocket = new WebSocket(\"ws://192.168.30.14:9090/triplan/websocket\"); // 서버 주소\r\n");
      out.write("\r\n");
      out.write("\t//웹 소켓이 연결되었을 때 호출되는 이벤트\r\n");
      out.write("\twebSocket.onopen = function(message){\r\n");
      out.write("\t\talert(\"연결성공\");\r\n");
      out.write("\t    webSocket.send(\"");
      out.print(member.getUserid());
      out.write("\");\r\n");
      out.write("\t};\r\n");
      out.write("\t//웹 소켓이 닫혔을 때 호출되는 이벤트\r\n");
      out.write("\twebSocket.onclose = function(message){\r\n");
      out.write("\t\twebSocket = new WebSocket(\"ws://192.168.30.14:9090/triplan/websocket\");\r\n");
      out.write("\t\talert(\"연결이 끊겼습니다.\");\r\n");
      out.write("\t};\r\n");
      out.write("\t//웹 소켓이 에러가 났을 때 호출되는 이벤트\r\n");
      out.write("\twebSocket.onerror = function(message){\r\n");
      out.write("\t\t alert(message); \r\n");
      out.write("\t};\r\n");
      out.write("\t//웹 소켓에서 메시지가 날라왔을 때 호출되는 이벤트\r\n");
      out.write("\twebSocket.onmessage = function(message){\r\n");
      out.write("\t\tjh_read(sc_idx);\r\n");
      out.write("\t};\r\n");
      out.write("\t//Send 버튼을 누르면 실행되는 함수\r\n");
      out.write("\tfunction save_sc(){\r\n");
      out.write("\t    webSocket.send(sc_idx+\"\");\r\n");
      out.write("\t}\r\n");
      out.write("\t//웹소켓 종료\r\n");
      out.write("\tfunction disconnect(){\r\n");
      out.write("\t\talert(\"연결종료\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(\"#totalscreen\").css(\"min-height\",($(window).height()-55)+\"px\");\r\n");
      out.write("\t\tjh_read(sc_idx);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#sc_searchWord\").focus(function(){\r\n");
      out.write("\t\t\t$(this).val(\"\");\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar j = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".search\").focus(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(this).keydown(function(event){\r\n");
      out.write("\t\t\t\tif(event.keyCode == 13)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tjh_getTourinfo('0');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#openIcon\").click(function(){\r\n");
      out.write("\t         \r\n");
      out.write("\t         if(j == 0) {\r\n");
      out.write("\t            $(\"#chatscreen\").css(\"border-width\",1);\r\n");
      out.write("\t            chatopen($(\"#leftscreen\"),0,$(\"#chatscreen\"),2.5,97.5);\r\n");
      out.write("\t            j = 999;\r\n");
      out.write("\t            setTimeout(function(){\r\n");
      out.write("\t               $(\"#chatroom\").show();\r\n");
      out.write("\t               j = 1;\r\n");
      out.write("\t                },350);\r\n");
      out.write("\t         } \r\n");
      out.write("\t         $(\"#openIcon\").hide();\r\n");
      out.write("\t         $(\"#closeIcon\").show();\r\n");
      out.write("\t      })\r\n");
      out.write("\t\t\r\n");
      out.write("\t      $(\"#closeIcon\").click(function(){\r\n");
      out.write("\t         \r\n");
      out.write("\t    \t  if(j == 1){\r\n");
      out.write("\t\t            $(\"#chatroom\").hide();\r\n");
      out.write("\t\t            chatclose($(\"#leftscreen\"),-12,$(\"#chatscreen\"),21.1,78.9);\r\n");
      out.write("\t\t            j = 999;\r\n");
      out.write("\t\t               setTimeout(function(){\r\n");
      out.write("\t\t                   $(\"#chatscreen\").css(\"border-width\",0);\r\n");
      out.write("\t\t                  j = 0;\r\n");
      out.write("\t\t                },350);\r\n");
      out.write("\t\t         }\r\n");
      out.write("\t\t         $(\"#closeIcon\").hide();\r\n");
      out.write("\t\t         $(\"#openIcon\").show();\r\n");
      out.write("\t      })\r\n");
      out.write("\t\t\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\tvar tdcount;\r\n");
      out.write("\tvar viewnum = 1;\r\n");
      out.write("\tvar sc_tourcount = 0;\r\n");
      out.write("\tvar sc_size = 0\r\n");
      out.write("    var touridxarr = new Array();\r\n");
      out.write("\tvar infowindows = new Array();\r\n");
      out.write("\tvar infowindowcount = 0;\r\n");
      out.write("\tvar openinfowindow = 0;\r\n");
      out.write("\t\r\n");
      out.write("\tvar map;\r\n");
      out.write("/////////////////////////\r\n");
      out.write("\r\n");
      out.write("\tfunction initialize(inscarr)\r\n");
      out.write("   {\r\n");
      out.write("\t   var mycenterX = $(inscarr).find(\".tx\").val();\r\n");
      out.write("\t   var mycenterY = $(inscarr).find(\".ty\").val();\r\n");
      out.write("\t   \r\n");
      out.write("\t   var mycenter = new google.maps.LatLng(mycenterX, mycenterY);\r\n");
      out.write("\t   \r\n");
      out.write("\t   var mapProp = {\r\n");
      out.write("\t     center:mycenter,\r\n");
      out.write("\t     zoom: 8,\r\n");
      out.write("\t     mapTypeId:google.maps.MapTypeId.ROADMAP\r\n");
      out.write("\t     };\r\n");
      out.write("\t    \r\n");
      out.write("\t   map=new google.maps.Map(document.getElementById(\"googleMap\"),mapProp);\r\n");
      out.write("\t   \r\n");
      out.write("\t   var t_idx = $(inscarr).find(\".t_idx\").val();\r\n");
      out.write("\t   var t_name = $(inscarr).find(\".t_name\").text();\r\n");
      out.write("\t   var t_type = $(inscarr).find(\".t_type\").val();\r\n");
      out.write("\t   var t_rating = $(inscarr).find(\".t_rating\").val();\r\n");
      out.write("\t   var tx = $(inscarr).find(\".tx\").val();\r\n");
      out.write("\t   var ty = $(inscarr).find(\".ty\").val();\r\n");
      out.write("\t   \r\n");
      out.write("\t   add_map(inscarr,t_idx,t_name,t_type,t_rating,tx,ty);\r\n");
      out.write("   }\r\n");
      out.write("\t   /////////////////////////////////\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction jh_write(sc_idx) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".jh_btn_left\").remove();\r\n");
      out.write("\t\t$(\".jh_btn_right\").remove();\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\tvar table = document.getElementById(\"timeTable\");\r\n");
      out.write("\t\tvar td = table.getElementsByTagName(\"td\");\r\n");
      out.write("\t\tvar tdarr = new Array();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(var i=0; i<td.length; i++)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ttdarr[i] = $(td[i]).html();\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tlr_btn_loca();\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\t$.ajax({\r\n");
      out.write(" \t\t\t  url: \"/triplan/schedule_Save.tp\",\r\n");
      out.write("\t\t      type: \"POST\",\r\n");
      out.write("\t\t      dataType : \"json\",\r\n");
      out.write("\t\t      data: {\r\n");
      out.write("\t\t    \t  sc_idx : sc_idx,\r\n");
      out.write("\t\t    \t  td : JSON.stringify(tdarr),\r\n");
      out.write("\t\t    \t  sc_days : tdcount\r\n");
      out.write("\t\t      },\r\n");
      out.write("\t\t      complete: function(data){\r\n");
      out.write("\t\t\t\tsave_sc();\r\n");
      out.write("\t\t      },\r\n");
      out.write("\t\t      error : function(xhr, status, error) {\r\n");
      out.write("\t            \r\n");
      out.write("\t           }\r\n");
      out.write("\t\t  }); \r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction jh_read(sc_idx) {\r\n");
      out.write("\t\t\r\n");
      out.write(" \t\t$.ajax({\r\n");
      out.write(" \t\t\t  url: \"/triplan/schedule_Load.tp\",\r\n");
      out.write("\t\t      type: \"POST\",\r\n");
      out.write("\t\t      data: {sc_idx : sc_idx, edit : \"y\"},\r\n");
      out.write("\t\t      dataType : \"html\",\r\n");
      out.write("\t\t      success: function(data){\r\n");
      out.write("  \t\t\t\t\t$(\"#jh_table\").html(data);\r\n");
      out.write("\t\t\t\t\t tdcount = parseInt($(\"#collen\").val());\r\n");
      out.write("\t\t\t\t\t lr_btn_loca()\r\n");
      out.write("\t\t\t\t\t if(tdcount < 5) $(\".jh_btn_right\").text(\"+\");\r\n");
      out.write("\t\t\t\t\t sc_init();\r\n");
      out.write("\t\t      }\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t  }); \r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction jh_appendTd() {\r\n");
      out.write("\t\tvar end_date = $(\"#jh_table thead .jh_sc_\"+(tdcount-1)).html();\r\n");
      out.write("\t\tend_date = end_date.substr(0,10).trim();\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t url: \"/triplan/appendDate.tp\",\r\n");
      out.write("\t\t      type: \"POST\",\r\n");
      out.write("\t\t      data: {end_date : end_date},\r\n");
      out.write("\t\t      success: function(data){\r\n");
      out.write("\t\t    \t  var date = data.trim();\r\n");
      out.write("\t\t  \t \t  $(\"#jh_table tr\").append(\"<td class='jh_sc_\"+tdcount+\"' ondrop='drop(event)' ondragover='allowDrop(event)' ondragleave='dragleave(event)' ></td>\");\r\n");
      out.write("\t\t\t\t  $(\"#jh_table thead .jh_sc_\"+tdcount).html(date);\r\n");
      out.write("\t\t\t\t  tdcount = tdcount + 1;\r\n");
      out.write("\t\t    \t  jh_right();\r\n");
      out.write("\t\t    \t  jh_write(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sc_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("\t\t      }\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction jh_left() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(viewnum > 1){\r\n");
      out.write("\t\t\t$(\".jh_sc_\"+(viewnum-1)).addClass(\"view\");\r\n");
      out.write("\t\t\t$(\".jh_sc_\"+(viewnum+2)).removeClass(\"view\");\r\n");
      out.write("\t\t\tviewnum = viewnum - 1;\r\n");
      out.write("\t\t\tlr_btn_loca()\r\n");
      out.write("\t\t\tif(viewnum < tdcount-3)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t$(\".jh_btn_right\").html(\"&nbsp;>&nbsp;&nbsp;\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction jh_right() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(viewnum < tdcount-3)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t$(\".jh_sc_\"+(viewnum+3)).addClass(\"view\");\r\n");
      out.write("\t\t\t$(\".jh_sc_\"+(viewnum)).removeClass(\"view\");\r\n");
      out.write("\t\t\tviewnum = viewnum + 1;\r\n");
      out.write("\t\t\tlr_btn_loca()\r\n");
      out.write("\t\t\tif(viewnum == tdcount-3)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t$(\".jh_btn_right\").html(\"&nbsp;+&nbsp;&nbsp;\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse \r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar yn = confirm(\"날짜를 추가하시겠습니까?\");\r\n");
      out.write("\t\t\tif(yn == true) \r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tjh_appendTd();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction lr_btn_loca()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$(\"#jh_table>thead>tr>td\").css(\"text-align\",\"center\");\r\n");
      out.write("\t\t$(\".jh_btn_left\").remove();\r\n");
      out.write("\t\t$(\".jh_btn_right\").remove();\r\n");
      out.write("\t\tvar theadleft = $(\"#jh_table\").find(\"thead\").find(\".jh_sc_\"+viewnum);\r\n");
      out.write("\t\tvar theadright = $(\"#jh_table\").find(\"thead\").find(\".jh_sc_\"+(viewnum+2));\r\n");
      out.write("\t\t$(theadleft).css(\"text-align\",\"left\");\r\n");
      out.write("\t\t$(theadright).css(\"text-align\",\"right\");\r\n");
      out.write("\t\t$(theadleft).html(\"<span class='jh_btn_left' onclick='jh_left()' style=' margin-right:12%;'>&nbsp;&nbsp;<&nbsp;</span>\"+$(theadleft).html());\r\n");
      out.write("\t\t$(theadright).html($(theadright).html()+\"<span class='jh_btn_right' onclick='jh_right()' style='margin-left:12%;'>&nbsp;>&nbsp;&nbsp;</span\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction chatclose(ls,lsl,div,width,left)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(width > 2.5)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t$(div).css(\"left\",(left+0.422)+\"%\");\r\n");
      out.write("\t\t\t$(div).css(\"width\",(width-0.422)+\"%\");\r\n");
      out.write("\t\t\t$(ls).css(\"margin-left\",(lsl+0.24)+\"%\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\tchatclose(ls,(lsl+0.24),div,(width-0.422),(left+0.422));  \t\r\n");
      out.write("\t        },1);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction chatopen(ls,lsl,div,width,left)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(width < 21.1)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t$(div).css(\"left\",(left-0.422)+\"%\");\r\n");
      out.write("\t\t\t$(div).css(\"width\",(width+0.422)+\"%\");\r\n");
      out.write("\t\t\t$(ls).css(\"margin-left\",(lsl-0.24)+\"%\");\r\n");
      out.write("\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\tchatopen(ls,(lsl-0.24),div,(width+0.422),(left-0.422));  \t\r\n");
      out.write("\t        },1);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction jh_getTourinfo(t_type){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar searchWord = $(\"#sc_searchWord\").val().trim();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(searchWord != null && searchWord != \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(searchWord == \"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"검색어를 입력하세요!\");\r\n");
      out.write("\t\t\t\tlocation.href=\"/triplan/searchArea.tp?de_area_name=\" + mycenter_name;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\telse if(searchWord == \"경기\" || searchWord == \"경기도\"\r\n");
      out.write("\t\t\t\t || searchWord == \"강원\" || searchWord == \"강원도\"\r\n");
      out.write("\t\t\t\t || searchWord == \"전라\" || searchWord == \"전라도\"\r\n");
      out.write("\t\t\t\t || searchWord == \"경상\" || searchWord == \"경상도\"\r\n");
      out.write("\t\t\t\t || searchWord == \"충청\" || searchWord == \"충청도\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"지역명이 정확하지 않습니다.\");\t\r\n");
      out.write("\t\t\t\tlocation.href=\"/triplan/searchArea.tp?de_area_name=\" + mycenter_name;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\telse if(searchWord.length < 2)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"지역명이 정확하지 않습니다.\");\t\r\n");
      out.write("\t\t\t\tlocation.href=\"/triplan/searchArea.tp?de_area_name=\" + mycenter_name;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar form_data={ area : searchWord\r\n");
      out.write("\t\t\t\t\t \t\t,t_type :t_type}\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.ajax({url: \"/triplan/sc_getTourinfo.tp\",\r\n");
      out.write("\t\t\t\t      type: \"GET\",\r\n");
      out.write("\t\t\t\t      data: form_data, // 서버로 보내는 ajax 요청 데이터\r\n");
      out.write("\t\t\t\t      dataType: \"html\", // ajax 요청에 의해 서버로 부터 리턴받는 데이터 타입. xml, html, json, text 가 있음.\r\n");
      out.write("\t\t\t\t      success: function(data){\r\n");
      out.write("\t\t\t\t    \t  \r\n");
      out.write("\t\t\t\t    \t  $(\".active\").removeClass(\"active\");\r\n");
      out.write("\t\t\t\t    \t  $(\"#jh_all\").addClass(\"active\");\r\n");
      out.write("\t\t\t\t    \t  $(\"#display_tlist\").html(data);  \t\t\t\t\r\n");
      out.write("\t\t\t\t    \t  \r\n");
      out.write("\t\t\t\t      },error:function(data){\r\n");
      out.write("\t\t\t\t    \t  \r\n");
      out.write("\t\t\t\t    \t  alert(\"지역명이 정확하지 않습니다.\");\t\r\n");
      out.write("\t\t\t\t      }\r\n");
      out.write("\t\t\t\t  });// end of $.ajax();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t$(\"#display_tlist\").html(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction jh_getWish(){\r\n");
      out.write("\t \r\n");
      out.write("\t \t $.ajax({url: \"/triplan/cd_getWishRegion.tp\",\r\n");
      out.write("\t    \t \r\n");
      out.write("\t \t  type: \"GET\",\r\n");
      out.write("\t      dataType: \"html\", \r\n");
      out.write("\t      data: { areano : 100 },\r\n");
      out.write("\t      success: function(data){\r\n");
      out.write("\t   \t   \r\n");
      out.write("\t\t\t$(\"#display_tlist\").html(data);  \t\t\t\r\n");
      out.write("\t\t\t           \r\n");
      out.write("\t      }// end of success----------------------\r\n");
      out.write("\t  });// end of $.ajax();----------------------\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction allowDrop(ev) {\r\n");
      out.write("\t\tvar html =  $(ev.target).html();\r\n");
      out.write("\t\tif(html == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t$(ev.target).css(\"background-color\",\"#f2f2f2\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    ev.preventDefault();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction dragleave(ev) {\r\n");
      out.write("\t\tvar html =  $(ev.target).html();\r\n");
      out.write("\t\tif(html == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t$(ev.target).css(\"background-color\",\"white\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t    ev.preventDefault();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction drag(ev) {\r\n");
      out.write("\t    ev.dataTransfer.setData(\"text\", ev.target.id);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction drop(ev) {\r\n");
      out.write("\t    ev.preventDefault();\r\n");
      out.write("\t    var data = ev.dataTransfer.getData(\"text\");\r\n");
      out.write("\t    var tn = document.getElementById(data);\r\n");
      out.write("\t    \r\n");
      out.write("\t    var target = event.target;\r\n");
      out.write("\t    \r\n");
      out.write("\t    var html = $(target).html();\r\n");
      out.write("\t    \r\n");
      out.write(" \t\tif($(tn).hasClass(\"copy\"))\r\n");
      out.write("\t\t{\r\n");
      out.write(" \t\t\tif(html == \"\")\r\n");
      out.write(" \t\t\t{\r\n");
      out.write(" \t\t\t\t$(target).css(\"background-color\",\"white\");\r\n");
      out.write(" \t\t\t    $(target).css(\"padding\",\"2px\");\r\n");
      out.write(" \t\t\t    \r\n");
      out.write("\t \t\t\tvar copy_tn = ev.target.appendChild(tn.cloneNode(true));\r\n");
      out.write("\t \t\t\t$(copy_tn).removeClass(\"copy\");\r\n");
      out.write("\t \t\t\t$(copy_tn).addClass(\"insc\");\r\n");
      out.write("\t \t\t\t$(copy_tn).append(\"<div style='display: inline-block; position: relative; left:87px; margin-top: -23px; color:blue; font-weight: bold;' onclick='romvetn(this);' >X</div>\");\r\n");
      out.write("\t \t\t\tvar t_idx = $(copy_tn).find(\".t_idx\").val();\r\n");
      out.write("\t \t\t\tvar t_name = $(copy_tn).find(\".t_name\").text();\r\n");
      out.write("\t \t\t\tvar t_type = $(copy_tn).find(\".t_type\").val();\r\n");
      out.write("\t \t\t\tvar tx = $(copy_tn).find(\".tx\").val();\r\n");
      out.write("\t \t\t\tvar ty = $(copy_tn).find(\".ty\").val();\r\n");
      out.write("\t \t\t\tvar t_rating = $(copy_tn).find(\".t_rating\").val();\r\n");
      out.write("\t\r\n");
      out.write("\t \t\t\t$(copy_tn).find(\".view_t_type\").remove();\r\n");
      out.write("\t \t\t\t\r\n");
      out.write("\t \t\t\tif(t_type == \"1\")\r\n");
      out.write("\t \t\t\t{\r\n");
      out.write("\t \t\t\t\t$(copy_tn).addClass(\"ti_on_sc1\"); \t\t\t\t\r\n");
      out.write("\t \t\t\t}\r\n");
      out.write("\t \t\t\telse if(t_type == \"2\")\r\n");
      out.write("\t \t\t\t{\r\n");
      out.write("\t \t\t\t\t$(copy_tn).addClass(\"ti_on_sc2\");\r\n");
      out.write("\t \t\t\t}\r\n");
      out.write("\t \t\t\telse if(t_type == \"3\")\r\n");
      out.write("\t \t\t\t{\r\n");
      out.write("\t \t\t\t\t$(copy_tn).addClass(\"ti_on_sc3\");\r\n");
      out.write("\t \t\t\t}\r\n");
      out.write("\t \t\t\telse\r\n");
      out.write("\t \t\t\t{\r\n");
      out.write("\t \t\t\t\t$(copy_tn).addClass(\"ti_on_sc4\");\r\n");
      out.write("\t \t\t\t}\r\n");
      out.write("\t \t\t    $(copy_tn).attr(\"id\",\"sc_tour\"+sc_tourcount);\r\n");
      out.write("\t \t\t    sc_tourcount++;\r\n");
      out.write("\t \t\t   \trefresh_map(copy_tn,t_idx,t_name,t_type,t_rating,tx,ty);\r\n");
      out.write("\t \t\t    jh_write(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sc_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\t \t\t \r\n");
      out.write(" \t\t\t}\r\n");
      out.write(" \t\t\telse\r\n");
      out.write(" \t\t\t{\r\n");
      out.write(" \t\t\t\talert(\"다른 일정이 존재합니다.\")\r\n");
      out.write(" \t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif(html == \"\")\r\n");
      out.write(" \t\t\t{\r\n");
      out.write("\t\t\t\t$(target).css(\"background-color\",\"white\");\r\n");
      out.write(" \t\t\t    $(target).css(\"padding\",\"2px\");\r\n");
      out.write("\t\t\t\tev.target.appendChild(tn);\r\n");
      out.write("\t\t\t\tjh_write(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sc_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write(" \t\t\t}\r\n");
      out.write("\t\t\telse\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\talert(\"다른 일정이 존재합니다.\")\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t} \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction refresh_map(insc,t_idx,t_name,t_type,t_rating,tx,ty)\r\n");
      out.write("\t{\r\n");
      out.write("\t\t var mycenterX = tx;\r\n");
      out.write("\t\t var mycenterY = ty;\r\n");
      out.write("\t\t var mycenter = new google.maps.LatLng(mycenterX, mycenterY);\r\n");
      out.write("\t\t map.setOptions({ 'center' : mycenter, 'zoom' : 16});\r\n");
      out.write("\t\t google.maps.event.addDomListener(window, 'load', add_map(insc,t_idx,t_name,t_type,t_rating,tx,ty));\r\n");
      out.write("\t\t \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction add_map(insc,t_idx,t_name,t_type,t_rating,tx,ty)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar mypositionX = tx;\r\n");
      out.write("\t\tvar mypositionY = ty;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar myposition = new google.maps.LatLng(mypositionX, mypositionY);\r\n");
      out.write("\t\tvar myposition_name = t_name+\"\";\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\tvar iconImage = \"\";\r\n");
      out.write("\t\tvar category = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(t_type == \"1\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ticonImage = \"/triplan/resources/image/tours.png\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse if(t_type == \"2\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ticonImage = \"/triplan/resources/image/restaurants.png\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse if(t_type == \"3\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ticonImage = \"/triplan/resources/image/lounges.png\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse if(t_type == \"4\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ticonImage = \"/triplan/resources/image/nightlife.png\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  var marker=new google.maps.Marker({\r\n");
      out.write("\t\t  position:myposition,\r\n");
      out.write("\t\t  icon:iconImage\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\t\tmarker.setMap(map);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar rating_str = t_rating;\r\n");
      out.write("\t\tvar rating_star = \"☆☆☆☆☆\";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar rating_num = parseFloat(rating_str);\r\n");
      out.write("\t\trating_num = Math.round(rating_num);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(rating_num == 1)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\trating_star = \"★☆☆☆☆\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse if(rating_num == 2)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\trating_star = \"★★☆☆☆\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse if(rating_num == 3)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\trating_star = \"★★★☆☆\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse if(rating_num == 4)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\trating_star = \"★★★★☆\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse if(rating_num == 5)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\trating_star = \"★★★★★\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tvar html = myposition_name + \" (\" + rating_star + \") <br/>\";\r\n");
      out.write("   \t\thtml += \"<img style='width:100%; height:120px;' src='/triplan/TourInfo/images/\"+t_idx+\"/title.jpg' /><br/>\";\r\n");
      out.write("   \t\thtml += \"<p></p>\";\r\n");
      out.write("\t    html += \"<a onClick='goDetail(\"+t_idx+\");' style='cursor: pointer;'>상세정보보기</a>\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tvar infowindow = new google.maps.InfoWindow({\r\n");
      out.write("\t\t\tcontent:html,\r\n");
      out.write("\t\t\tmaxWidth: 200\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tinfowindows.push(infowindow);\r\n");
      out.write("\t\tvar temp = infowindowcount;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tgoogle.maps.event.addListener(marker, 'click', function() {\r\n");
      out.write("\t\t\tinfowindows[openinfowindow].close();\r\n");
      out.write("\t\t\tinfowindow.open(map,marker);\r\n");
      out.write("\t\t\topeninfowindow = temp; \r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(insc).click(function(){\r\n");
      out.write("\t\t\t  var test = infowindowcount;\r\n");
      out.write("\t\t\t  infowindows[openinfowindow].close();\r\n");
      out.write("\t    \t  infowindow.open(map,marker);\r\n");
      out.write("\t    \t  openinfowindow = temp;\r\n");
      out.write("\t      })\r\n");
      out.write("\t      \r\n");
      out.write("\t\tsc_size++;\r\n");
      out.write("\t\tinfowindowcount++;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction sc_init()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar inscarr = document.getElementsByClassName(\"insc\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(inscarr[0] != null)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t$(inscarr[0]).attr(\"id\",\"sc_tour\"+(sc_tourcount++));\r\n");
      out.write("\t\t\t$(inscarr[0]).parent().css(\"padding\",\"2px\");\r\n");
      out.write("\t\t\ttouridxarr[0] = $(inscarr[0]).find(\".t_idx\").val();\r\n");
      out.write("\t\t\tgoogle.maps.event.addDomListener(window, 'load', initialize(inscarr[0]));\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t \tfor(var i = 1; i < inscarr.length; i++)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t \t\t$(inscarr[i]).attr(\"id\",\"sc_tour\"+(sc_tourcount++));\r\n");
      out.write("\t\t\t\t$(inscarr[i]).parent().css(\"padding\",\"2px\");\r\n");
      out.write("\t\t\t\ttouridxarr[i] = $(inscarr[i]).find(\".t_idx\").val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar t_idx = $(inscarr[i]).find(\".t_idx\").val();\r\n");
      out.write("\t\t\t\tvar t_name = $(inscarr[i]).find(\".t_name\").text();\r\n");
      out.write("\t\t\t\tvar t_type = $(inscarr[i]).find(\".t_type\").val();\r\n");
      out.write("\t\t\t\tvar t_rating = $(inscarr[i]).find(\".t_rating\").val();\r\n");
      out.write("\t\t\t\tvar tx = $(inscarr[i]).find(\".tx\").val();\r\n");
      out.write("\t\t\t\tvar ty = $(inscarr[i]).find(\".ty\").val();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tgoogle.maps.event.addDomListener(window, 'load', add_map(inscarr[i],t_idx,t_name,t_type,t_rating,tx,ty));\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t \t \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tgoogle.maps.event.addDomListener(window, 'load', noinsc_map());\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t   function noinsc_map()\r\n");
      out.write("\t   {\r\n");
      out.write("\t\t   var mycenterX = 36.568993;\r\n");
      out.write("\t\t   var mycenterY = 128.032776;\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   var mycenter = new google.maps.LatLng(mycenterX, mycenterY);\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   var mapProp = {\r\n");
      out.write("\t\t     center:mycenter,\r\n");
      out.write("\t\t     zoom: 7,\r\n");
      out.write("\t\t     mapTypeId:google.maps.MapTypeId.ROADMAP\r\n");
      out.write("\t\t     };\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t   map=new google.maps.Map(document.getElementById(\"googleMap\"),mapProp);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t   \r\n");
      out.write("\t\tfunction goDetail(t_idx)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar url = \"detailTourInfo.tp?t_idx=\"+t_idx;\r\n");
      out.write("\t\t\twindow.open(url, \"detailTourInfo\",\r\n");
      out.write("\t\t\t\t\t\"width=665px, height=750px, top=70px, left=300px, resizable=no, status=no, scrollbars=yes, menubar=no\"\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction romvetn(tn)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tvar yn = confirm($(tn).parent().find(\".t_name\").text()+\"를 지우시겠습니까?\");\r\n");
      out.write("\t\t\tif(yn == true)\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\t$(tn).parent().remove();\r\n");
      out.write("\t\t\t\tjh_write(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sc_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction invite(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar url = \"inviteSchedule.tp?sc_idx=\"+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sc_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\t\twindow.open(url, \"Invite\",\r\n");
      out.write("\t\t\t\t\t\"width=665px, height=700px, top=70px, left=300px, resizable=no, status=no, scrollbars=yes, menubar=no\"\r\n");
      out.write("\t\t\t);\r\n");
      out.write("\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tfunction map_select()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\t\t$(\"#googleMap\").find(\".gm-style\").append(\"<div class='gmnoprint gmselect' style='border: 1px solid red; width: 150px; height: 150px'><div>\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"screen\">\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../top.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div id=\"totalscreen\">\r\n");
      out.write("\t    <div id=\"leftscreen\">\r\n");
      out.write("      \t\t<div id=\"googleMap\"></div>\r\n");
      out.write("      \t\t<div id=\"edsc_search\" style=\"width: 100%; padding-left: 4%;\" >\r\n");
      out.write("      \t\t\t<button type=\"button\" class=\"btn btn-default\" onclick=\"invite()\" style=\"float: left; margin-top: 10px; height: 30px !important; margin-right: 3%; padding: 1px 3px 1px 3px !important;\" >일정초대</button>\r\n");
      out.write("      \t\t\t<input type=\"text\" class=\"search\" id=\"sc_searchWord\" style=\"height: 30px !important; width: 56% !important\">\r\n");
      out.write("\t\t\t\t\t<button style=\"height: 30px !important; padding: 0px 9px !important; \" type=\"button\" class=\"btn btn-default btn-lg btn-search\" onClick=\"jh_getTourinfo('0');\"><span class=\"glyphicon glyphicon-search\" style=\"top: 1px !important;\"></span> <span class=\"span-search\"></span>검색</button>\r\n");
      out.write("      \t\t</div>\r\n");
      out.write("\t      \t<div id=\"list\">\r\n");
      out.write("\t      \t\t<ul class=\"nav nav-tabs\">\r\n");
      out.write("\t\t\t  \t\t<li id=\"jh_all\" class=\"active\"><a data-toggle=\"tab\" onclick=\"jh_getTourinfo('0');\">전체</a></li>\r\n");
      out.write("\t\t\t\t  \t<li><a data-toggle=\"tab\" onclick=\"jh_getWish();\">위시리스트</a></li>\r\n");
      out.write("\t\t\t\t  \t<li><a data-toggle=\"tab\" onclick=\"jh_getTourinfo('1');\">관광</a></li>\r\n");
      out.write("\t\t\t\t  \t<li><a data-toggle=\"tab\" onclick=\"jh_getTourinfo('2');\">음식</a></li>\r\n");
      out.write("\t\t\t\t  \t<li><a data-toggle=\"tab\" onclick=\"jh_getTourinfo('3');\">숙박</a></li>\r\n");
      out.write("\t\t\t\t  \t<li><a data-toggle=\"tab\" onclick=\"jh_getTourinfo('4');\">기타</a></li>\r\n");
      out.write("\t\t\t  \t</ul>\r\n");
      out.write("\t\t\t\t<div id=\"display_tlist\">\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("     \t \t</div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t    <div id=\"rightscreen\">\r\n");
      out.write("\t\t\t<div id=\"timeTable\">\r\n");
      out.write("\t\t\t  <table id=\"jh_table\" class=\"table table-bordered\" style=\"color: #000000;\">\r\n");
      out.write("\t\t\t  </table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div id=\"chatscreen\">\r\n");
      out.write("\t\t\t<div id=\"openIcon\" style=\"cursor: pointer; width:13%; height:15%; position:absolute; left:2px; top:0px; z-index:1;\">\r\n");
      out.write("\t\t\t\t<img src=\"/triplan/resources/image/chat.png\" style=\"width:30px; height:30px;\">\r\n");
      out.write("\t\t\t\t<br/><span style=\"color:gray;\">open</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"chatroom\">\r\n");
      out.write("\t\t\t\t\t<div id=\"closeIcon\" style=\"cursor: pointer; width:13%; height:13%; position:absolute; left:2px; top:0px; z-index:1;\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/triplan/resources/image/chat.png\" style=\"width:30px; height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t<br/><span style=\"color:gray;\">close</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"width:100%; height:97.5%; position:relative;\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "chat.jsp", out, false);
      out.write("</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../foot.jsp", out, false);
      out.write("\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/schedule/editSchedule.jsp(862,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tourinfoList == null || empty tourinfoList }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("<div>지역정보가 없습니다.</div>");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/views/schedule/editSchedule.jsp(863,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tourinfoList != null && not empty tourinfoList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write("\t\r\n");
        out.write("\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /WEB-INF/views/schedule/editSchedule.jsp(864,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("vo");
    // /WEB-INF/views/schedule/editSchedule.jsp(864,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/schedule/editSchedule.jsp(864,5) '${tourinfoList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${tourinfoList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/schedule/editSchedule.jsp(864,5) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVarStatus("sts");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<div id=\"ti");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sts.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"  draggable=\"true\" ondragstart=\"drag(event)\" class=\"copy\">\r\n");
          out.write("\t\t\t\t\t<div style=\"width: 100%;\">\r\n");
          out.write("\t\t\t\t\t\t<img src=\"/triplan/TourInfo/images/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.t_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/title.jpg\" style=\"height: 10%; width: 10%;\">\r\n");
          out.write("\t\t\t\t\t\t<span class=\"t_name\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.t_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</span>\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.t_idx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"t_idx\"/>\r\n");
          out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.t_type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"t_type\"/>\r\n");
          out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.t_rating}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"t_rating\"/>\r\n");
          out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.tx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"tx\"/>\r\n");
          out.write("\t\t\t\t\t\t<input type=\"hidden\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.ty}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"ty\"/>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/schedule/editSchedule.jsp(869,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.t_type == '1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t <span style=\"color: #3399ff\" class=\"view_t_type\">관광</span>\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/schedule/editSchedule.jsp(872,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.t_type == '2'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t <span style=\"color: #e6005c\" class=\"view_t_type\">음식</span>\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/schedule/editSchedule.jsp(875,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.t_type == '3'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
    if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t <span style=\"color: #0033cc\" class=\"view_t_type\">숙박</span>\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/schedule/editSchedule.jsp(878,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.t_type == '4'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
    if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t <span style=\"color: #ff5c33\" class=\"view_t_type\">기타</span>\r\n");
        out.write("\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
    return false;
  }
}
