/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-07-07 02:20:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.search;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.spring.model.*;
import java.util.*;

public final class searchArea_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/triplanworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Triplan/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1463983535931L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.spring.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<script src=\"http://maps.googleapis.com/maps/api/js\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/jquery-2.0.0.js\" ></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\t#totalscreen{\r\n");
      out.write("\t\tpadding-top: 52px;\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\tmin-height: 100%;\r\n");
      out.write("\t\theight: auto;\r\n");
      out.write("\t\tclear: both;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#leftscreen {\r\n");
      out.write("\t\twidth:35%;\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\tmargin-left: 5%;\r\n");
      out.write("\t\tpadding-left:10px;\r\n");
      out.write("\t\tpadding-top: 1.5%;\r\n");
      out.write("\t\tborder:0px solid orange;\r\n");
      out.write(" \t}\r\n");
      out.write("  \r\n");
      out.write("\t#rightscreen {\r\n");
      out.write("\t\twidth:55%;\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\tmargin-right: 5%;\r\n");
      out.write("\t\tpadding-right:10px;\r\n");
      out.write("\t\tpadding-top:2%;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#gh_searchArea-form {\r\n");
      out.write("\t\twidth: 40%;\r\n");
      out.write("\t\ttop: 52px;\t\r\n");
      out.write("\t\tposition:absolute;\r\n");
      out.write("\t\tmargin-bottom: -5%;\r\n");
      out.write("\t\tz-index: 1000;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#googleMap {\r\n");
      out.write("\t\t width:100%;\r\n");
      out.write("\t\t height: 80%;\r\n");
      out.write("\t\t /* margin-bottom: 4.5%; */\r\n");
      out.write("\t\t margin-left:2%;\r\n");
      out.write("\t\r\n");
      out.write("\t\t border:0px solid orange;\r\n");
      out.write("\t\t border-radius: 1% !important;\r\n");
      out.write("\t\t \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#timeTable {\r\n");
      out.write("\t\t width:100%;\r\n");
      out.write("\t\t float:left;\r\n");
      out.write("\t\t padding-left:10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#list {\r\n");
      out.write("\t\t margin-top: 47px;\r\n");
      out.write("\t\t width:100%;\r\n");
      out.write("\t\t height: 70%;\r\n");
      out.write("\t\t overflow:hidden;\r\n");
      out.write("\t\t padding-right:10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var mycenterX = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${advo.x}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("var mycenterY = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${advo.y}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("var mycenter=new google.maps.LatLng(mycenterX, mycenterY);\r\n");
      out.write("\r\n");
      out.write("var mycenter_name = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${advo.de_area_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("function initialize()\r\n");
      out.write("{\r\n");
      out.write("\tvar mapProp = {\r\n");
      out.write("\t  center:mycenter,\r\n");
      out.write("\t  zoom:10,\r\n");
      out.write("\t  mapTypeId:google.maps.MapTypeId.ROADMAP\r\n");
      out.write("\t  };\r\n");
      out.write("\t\r\n");
      out.write("\tvar map=new google.maps.Map(document.getElementById(\"googleMap\"),mapProp);\r\n");
      out.write("\t\r\n");
      out.write("\t");

		int count = 1;
		List<TourInfoVO> tlist = (List<TourInfoVO>)request.getAttribute("tourinfoList");
		for(TourInfoVO tvo : tlist)
		{
	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\tvar mypositionX = ");
      out.print( tvo.getTx() );
      out.write(";\r\n");
      out.write("\t\t\tvar mypositionY = ");
      out.print( tvo.getTy() );
      out.write(";\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\tvar myposition = new google.maps.LatLng(mypositionX, mypositionY);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar myposition_name = \"");
      out.print( tvo.getT_name() );
      out.write("\";\r\n");
      out.write("\t\t\tvar iconImage = \"\";\r\n");
      out.write("\t\t\tvar category = 0;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(");
      out.print( tvo.getT_type() );
      out.write(" == \"1\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\ticonImage = \"/triplan/resources/image/tours.png\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\telse if(");
      out.print( tvo.getT_type() );
      out.write(" == \"2\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\ticonImage = \"/triplan/resources/image/restaurants.png\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\telse if(");
      out.print( tvo.getT_type() );
      out.write(" == \"3\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\ticonImage = \"/triplan/resources/image/lounges.png\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\telse if(");
      out.print( tvo.getT_type() );
      out.write(" == \"4\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\ticonImage = \"/triplan/resources/image/nightlife.png\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar marker");
      out.print(count);
      out.write("=new google.maps.Marker({\r\n");
      out.write("\t\t\t  position:myposition,\r\n");
      out.write("\t\t\t  icon:iconImage\r\n");
      out.write("\t\t\t  });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tmarker");
      out.print(count);
      out.write(".setMap(map);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#menutop\").click(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tmarker");
      out.print(count);
      out.write(".setMap(map);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\".tour\").click(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tmarker");
      out.print(count);
      out.write(".setMap(null);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(");
      out.print( tvo.getT_type() );
      out.write(" == \"1\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tmarker");
      out.print(count);
      out.write(".setMap(map);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\".food\").click(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tmarker");
      out.print(count);
      out.write(".setMap(null);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(");
      out.print( tvo.getT_type() );
      out.write(" == \"2\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tmarker");
      out.print(count);
      out.write(".setMap(map);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\".hotel\").click(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tmarker");
      out.print(count);
      out.write(".setMap(null);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(");
      out.print( tvo.getT_type() );
      out.write(" == \"3\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tmarker");
      out.print(count);
      out.write(".setMap(map);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\".show\").click(function(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tmarker");
      out.print(count);
      out.write(".setMap(null);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(");
      out.print( tvo.getT_type() );
      out.write(" == \"4\")\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tmarker");
      out.print(count);
      out.write(".setMap(map);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write(" \t\t\t\t");

 				List<String> t_detail_list = new ArrayList<String>();
					if(tvo.getT_detail() != null)
					{
 					String t_detail = tvo.getT_detail();
 					if(tvo.getT_detail().length() > 30)
 					{
 						t_detail = tvo.getT_detail().substring(0, 30) + "...";
 					}
 					
 					Scanner sc = new Scanner(t_detail);
 					
 					while(sc.hasNextLine())
 					{
 						t_detail_list.add(sc.nextLine());
 					}	 				
 					sc.close();
					}
 				
      out.write(" \r\n");
      out.write("\t\t\t\r\n");
      out.write(" \t\t\t\tvar rating_str = \"");
      out.print( tvo.getT_rating() );
      out.write("\";\r\n");
      out.write(" \t\t\t\tvar rating_star = \"☆☆☆☆☆\";\r\n");
      out.write(" \t\t\t\t\r\n");
      out.write(" \t\t\t\tvar rating_num = parseFloat(rating_str);\r\n");
      out.write(" \t\t\t\trating_num = Math.round(rating_num);\r\n");
      out.write(" \t\t\t\t\r\n");
      out.write(" \t\t\t\tif(rating_num == 1)\r\n");
      out.write(" \t\t\t\t{\r\n");
      out.write(" \t\t\t\t\trating_star = \"★☆☆☆☆\";\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t\t\r\n");
      out.write(" \t\t\t\telse if(rating_num == 2)\r\n");
      out.write(" \t\t\t\t{\r\n");
      out.write(" \t\t\t\t\trating_star = \"★★☆☆☆\";\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t\t\r\n");
      out.write(" \t\t\t\telse if(rating_num == 3)\r\n");
      out.write(" \t\t\t\t{\r\n");
      out.write(" \t\t\t\t\trating_star = \"★★★☆☆\";\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t\t\r\n");
      out.write(" \t\t\t\telse if(rating_num == 4)\r\n");
      out.write(" \t\t\t\t{\r\n");
      out.write(" \t\t\t\t\trating_star = \"★★★★☆\";\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t\t\r\n");
      out.write(" \t\t\t\telse if(rating_num == 5)\r\n");
      out.write(" \t\t\t\t{\r\n");
      out.write(" \t\t\t\t\trating_star = \"★★★★★\";\r\n");
      out.write(" \t\t\t\t}\r\n");
      out.write(" \t\t\t\t\r\n");
      out.write("\t\t\t\tvar html = myposition_name + \" (\" + rating_star + \") <br/>\";\r\n");
      out.write("\t\t   \t\thtml += \"<img style='width:100%; height:120px;' src='/triplan/TourInfo/images/");
      out.print( tvo.getT_idx() );
      out.write("/title.jpg' /><br/>\";\r\n");
      out.write("\t\t   \t\thtml += \"<p>\";\r\n");
      out.write("\t\t\t   \t");
 
					if(tvo.getT_detail() != null)
					{
			   		for(int i=0; i < t_detail_list.size() ; i++)
			   		{ 
			   			
			   		
      out.write("\r\n");
      out.write("\t\t\t   \t\t\thtml += \"");
      out.print( t_detail_list.get(i) );
      out.write("\" \t\r\n");
      out.write("\t\t\t   \t\t");

			   		} 
		   		}
		   		
      out.write("\r\n");
      out.write("\t\t   \t\thtml += \"</p>\";\r\n");
      out.write("\t\t\t    html += \"<a onClick='goDetail(");
      out.print( tvo.getT_idx() );
      out.write(");' style='cursor: pointer;'>상세정보보기</a>\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar infowindow");
      out.print( count );
      out.write(" = new google.maps.InfoWindow({\r\n");
      out.write("\t\t\t\t\t\tcontent:html,\r\n");
      out.write("\t\t\t\t\t\tmaxWidth: 200\r\n");
      out.write("\t\t\t\t  });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tgoogle.maps.event.addListener(marker");
      out.print(count);
      out.write(", 'click', function() {\r\n");
      out.write("\t\t\t\t  \t\tinfowindow");
      out.print(count);
      out.write(".open(map,marker");
      out.print(count);
      out.write(");\r\n");
      out.write("\t\t\t\t  });\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#myplan>table>tbody>tr\").find(\".\"+");
      out.print(count);
      out.write(").click(function(){\r\n");
      out.write("\t\t\t\tinfowindow");
      out.print(count);
      out.write(".open(map,marker");
      out.print(count);
      out.write(");\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\r\n");
      out.write("\t\t\t");

			count++;
		} 
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tgoogle.maps.event.addDomListener(window, 'load', initialize);\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("var de_area_nameArr;\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#de_area_name\").keyup(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar form_data = {\r\n");
      out.write("\t\t\t\t\t\t\tde_area_name : $(\"#de_area_name\").val(),  // 키값 : 밸류값 \r\n");
      out.write("\t\t\t\t\t\t\tis_ajax : 1004                        // 키값 : 밸류값\r\n");
      out.write("\t\t                };\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"/triplan/autoSearch.tp\",\r\n");
      out.write("\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\tdata: form_data, // \"/triplan/autoSearch.tp\" 으로 보내야할 요청 데이터값 \r\n");
      out.write("\t\t\t\tdataType: \"html\",\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tvar resultText = data;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar resultArr = resultText.split('|'); // 리턴타입이 문자열을 가지는 배열로 리턴한다.\r\n");
      out.write("\t\t\t\t\tvar count = parseInt(resultArr[0]); // 4\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(count > 0) {\r\n");
      out.write("\t\t\t\t\t\tde_area_nameArr = resultArr[1].split(','); // 자바 프로그래밍,자바공부,자바프로그래머 김태균,자바\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar resultHtml = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tresultHtml += \"검색어 자동완성 <br/>\";\r\n");
      out.write("\t\t\t\t\t\tfor(var i=0; i<de_area_nameArr.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\tresultHtml += \"<a href='javascript:mychoose(\\\"\"+de_area_nameArr[i]+\"\\\")'>\"+de_area_nameArr[i] +\"</a><br/>\";\r\n");
      out.write("\t\t\t\t\t\t}// end of for-------------\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#displayList\").html(resultHtml);\r\n");
      out.write("\t\t\t\t\t\t$(\"#display\").show();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{ // 검색어로 시작하는 데이터가 없다라면\r\n");
      out.write("\t\t\t\t\t\t$(\"#display\").hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}// end of success-----------------\r\n");
      out.write("\t\t});// end of $.ajax()----------------------\r\n");
      out.write("\t\t\r\n");
      out.write("\t});// end of $(\"#de_area_name\").keyup()-----------\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function mychoose(title) {\r\n");
      out.write("\t$(\"#de_area_name\").val(title);\r\n");
      out.write("\t$(\"#display\").hide();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".search\").focus(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(this).keydown(function(event){\r\n");
      out.write("\t\t\t\tif(event.keyCode == 13)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tgoSearch();\r\n");
      out.write("\t\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t$(\"footer\").css(\"margin-top\",\"-55px\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#de_area_name\").focus(\r\n");
      out.write("\t\t\t    function(){\r\n");
      out.write("\t\t\t        $(this).val('');\r\n");
      out.write("\t\t\t    });\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(\".table\").mouseover(function(){\r\n");
      out.write("\t\t\t$(\"#list\").css(\"overflow\", \"auto\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".table\").mouseout(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#list\").css(\"overflow\", \"hidden\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goSearch()\r\n");
      out.write("\t{\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 유효성 검사!\r\n");
      out.write("\t\tvar de_area_name = document.getElementById(\"de_area_name\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(de_area_name == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"검색어를 입력하세요!\");\r\n");
      out.write("\t\t\tlocation.href=\"/triplan/searchArea.tp?de_area_name=\" + mycenter_name;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse if(de_area_name == \"경기\" || de_area_name == \"경기도\"\r\n");
      out.write("\t\t\t || de_area_name == \"강원\" || de_area_name == \"강원도\"\r\n");
      out.write("\t\t\t || de_area_name == \"전라\" || de_area_name == \"전라도\"\r\n");
      out.write("\t\t\t || de_area_name == \"경상\" || de_area_name == \"경상도\"\r\n");
      out.write("\t\t\t || de_area_name == \"충청\" || de_area_name == \"충청도\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"지역명이 정확하지 않습니다.\");\t\r\n");
      out.write("\t\t\tlocation.href=\"/triplan/searchArea.tp?de_area_name=\" + mycenter_name;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse if(de_area_name.length < 2)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"지역명이 정확하지 않습니다.\");\t\r\n");
      out.write("\t\t\tlocation.href=\"/triplan/searchArea.tp?de_area_name=\" + mycenter_name;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdocument.searchFrm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction searchKeep()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\twindow.onload = function()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tsearchKeep();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction goDetail(t_idx)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar url = \"detailTourInfo.tp?t_idx=\"+t_idx;\r\n");
      out.write("\t\twindow.open(url, \"detailTourInfo\",\r\n");
      out.write("\t\t\t\t\"width=665px, height=750px, top=70px, left=300px, resizable=no, status=no, scrollbars=yes, menubar=no\"\r\n");
      out.write("\t\t);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction getTourinfo(t_type){\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar form_data={ area : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${advo.de_area_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("\t\t\t \t\t,t_type :t_type}\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({url: \"/triplan/getTourinfo.tp\",\r\n");
      out.write("\t\t      type: \"GET\",\r\n");
      out.write("\t\t      data: form_data, // 서버로 보내는 ajax 요청 데이터\r\n");
      out.write("\t\t      dataType: \"html\", // ajax 요청에 의해 서버로 부터 리턴받는 데이터 타입. xml, html, json, text 가 있음.\r\n");
      out.write("\t\t      success: function(data){\r\n");
      out.write("\t\t    \t  var result = data;\r\n");
      out.write("\t\t    \t  $(\"#myplan\").empty();\r\n");
      out.write("\t\t    \t  $(\"#here1\").html(result);  \t\t\t\t\r\n");
      out.write("\t\t\t\t\t  \t\t\t\t\t\r\n");
      out.write("\t           \r\n");
      out.write("\t\t      },error:function(data){\r\n");
      out.write("\t\t    \t  \r\n");
      out.write("\t\t    \t  alert(\"error\");\r\n");
      out.write("\t\t      }\r\n");
      out.write("\t\t  });// end of $.ajax();\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write(" \r\n");
      out.write("window.onload=function(){\r\n");
      out.write("\tsearchKeep();\r\n");
      out.write("}\r\n");
      out.write("function searchKeep(){\r\n");
      out.write("\t\r\n");
      out.write("\tdocument.getElementById(\"de_area_name\").value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${advo.de_area_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\t\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"screen\">\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../top.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"totalscreen\">\r\n");
      out.write("\t    <div id=\"leftscreen\">\r\n");
      out.write("\t\t\t<form id=\"gh_searchArea-form\" name=\"searchFrm\" action=\"/triplan/searchArea.tp\" method=\"get\">\r\n");
      out.write("\t\t\t<div class=\"gh_search-box\" align=\"center\" style=\"z-index:100;\">\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"search search3\" id=\"de_area_name\" name=\"de_area_name\" size=\"30\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-lg btn-search\" onClick=\"goSearch();\"><span class=\"glyphicon glyphicon-search\"></span> <span class=\"span-search\"></span>검색</button>\r\n");
      out.write("\t\t\t\t<div id=\"display\" class=\"search2\" style=\"display:none; text-align:left;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"displayList\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t      \t<div id=\"list\" style=\"z-index:-11;\">\r\n");
      out.write("\t      \t\t      \t\r\n");
      out.write("\t      \t<ul class=\"nav nav-tabs\" id=\"tabs\" style=\"width:100%\">\r\n");
      out.write("\t\t\t  \t<li style=\"width:15%\"  class=\"all\" class=\"active\" id=\"menutop\" ><a  style=\"font-size:10pt; \" data-toggle=\"tab\" href=\"#myplan\" onclick=\"getTourinfo('0');\">전체</a></li>\r\n");
      out.write("\t\t\t  \t<li style=\"width:20%\" id=\"cd_topmenu\" class=\"tour\" ><a  style=\"text-decoration:none ; font-size:10pt; font-weight:bold; color:#3399ff;\" data-toggle=\"tab\" href=\"#mytour\" onclick=\"getTourinfo('1');\">관광</a></li>\r\n");
      out.write("\t\t\t  \t<li style=\"width:20%\" id=\"cd_topmenu\" class=\"food\" ><a  style=\"text-decoration:none ; font-size:10pt;font-weight:bold;  color:#e6005c; \" data-toggle=\"tab\" href=\"#myfood\" onclick=\"getTourinfo('2');\">음식</a></li>\r\n");
      out.write("\t\t\t  \t<li style=\"width:20%\" id=\"cd_topmenu\" class=\"hotel\" ><a style=\"text-decoration:none ; font-size:10pt;font-weight:bold; color:#0033cc;\" data-toggle=\"tab\" href=\"#myhotel\" onclick=\"getTourinfo('3');\">숙박</a></li>\r\n");
      out.write("\t\t\t  \t<li style=\"width:25%\" id=\"cd_topmenu\" class=\"show\" ><a style=\"text-decoration:none ; font-size:10pt;font-weight:bold; color:#ff5c33;\" data-toggle=\"tab\" href=\"#myshow\" onclick=\"getTourinfo('4');\">기타</a></li>\r\n");
      out.write("\t\t  \t</ul>\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\t  \t<div class=\"tab-content\">\r\n");
      out.write("  \r\n");
      out.write("\t\t    <div id=\"myplan\" class=\"tab-pane fade in active\" onclick=\"getTourinfo('0');\">\r\n");
      out.write("\t\t\t<table class=\"table table-condensed\" style=\"width: 100%\" >\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr class=\"success\">\r\n");
      out.write("\t\t\t         \t<td style=\"width: 10%\">번호</td>\r\n");
      out.write("\t\t\t         \t<td style=\"width: 30%\">상호명</td>\r\n");
      out.write("\t\t\t         \t<td style=\"width: 50%\">주소</td>\r\n");
      out.write("\t\t\t         \t<td style=\"width: 10%\">분류</td>\r\n");
      out.write("\t\t\t      \t</tr>\r\n");
      out.write("\t\t\t    </thead>\r\n");
      out.write("\t\t\t     <tbody>\r\n");
      out.write("\t\t\t      ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t  ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t    \t</tbody> \r\n");
      out.write("\t\t    \t\r\n");
      out.write("  \t\t \t</table>\r\n");
      out.write("  \t\t \t\r\n");
      out.write("  \t\t \t\r\n");
      out.write("     \t \t</div> \r\n");
      out.write("     \t \t\r\n");
      out.write("     \t <div id=\"mytour\" class=\"tab-pane fade\" onclick=\"getTourinfo('1');\" ></div>\t  \t \r\n");
      out.write("     \t <div id=\"myfood\" class=\"tab-pane fade\" onclick=\"getTourinfo('2');\"> </div>\t   \t \r\n");
      out.write("     \t <div id=\"myhotel\" class=\"tab-pane fade\" onclick=\"getTourinfo('3');\"></div>\t\t\t \r\n");
      out.write("     \t <div id=\"myshow\" class=\"tab-pane fade\" onclick=\"getTourinfo('4');\"> </div>\t\t\r\n");
      out.write("     \t <div id=\"here1\"></div>\r\n");
      out.write("     \t \t\r\n");
      out.write("     \t \t</div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("     \t  \t\t \r\n");
      out.write("\t    <div id=\"rightscreen\">\r\n");
      out.write("\t\t    <div id=\"googleMap\">\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../foot.jsp", out, false);
      out.write("\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/search/searchArea.jsp(403,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty de_area_name}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t// 자바스크립트 내에서 \"&{colName != null}\" 이렇게 하면 오류가 난다.\r\n");
        out.write("\t\t// 자바스크립트 내에서는  empty 를 사용해야 한다.\r\n");
        out.write("\t\t\tdocument.getElementById(\"de_area_name\").value = \"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${advo.de_area_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\";\r\n");
        out.write("\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/views/search/searchArea.jsp(498,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tourinfoList == null || empty tourinfoList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t <tr><td colspan=\"4\">존재하지 않습니다.</td></tr>\r\n");
        out.write("\t\t\t\t  ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /WEB-INF/views/search/searchArea.jsp(501,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tourinfoList != null || not empty tourinfoList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t \t ");
        if (_jspx_meth_c_005fset_005f0(_jspx_th_c_005fif_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t \t ");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t  \t ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
    // /WEB-INF/views/search/searchArea.jsp(502,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("count");
    // /WEB-INF/views/search/searchArea.jsp(502,7) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/search/searchArea.jsp(502,7) '0'",_jsp_getExpressionFactory().createValueExpression("0",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
    // /WEB-INF/views/search/searchArea.jsp(503,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("vo");
    // /WEB-INF/views/search/searchArea.jsp(503,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/search/searchArea.jsp(503,7) '${tourinfoList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${tourinfoList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    // /WEB-INF/views/search/searchArea.jsp(503,7) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVarStatus("status");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t  <tr>\r\n");
          out.write("\t\t\t\t\t\t  \t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index + 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t  \t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.t_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t  \t<td>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.t_addr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</td>\r\n");
          out.write("\t\t\t\t\t\t  \t");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f6(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t  </tr>\r\n");
          out.write("\t\t\t\t  \t ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/search/searchArea.jsp(508,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.t_type == '1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t <td>관광</td>\r\n");
        out.write("\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/search/searchArea.jsp(511,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.t_type == '2'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
    if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t <td>음식</td>\r\n");
        out.write("\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/search/searchArea.jsp(514,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.t_type == '3'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
    if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t <td>숙박</td>\r\n");
        out.write("\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/search/searchArea.jsp(517,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vo.t_type == '4'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
    if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t\t <td>기타</td>\r\n");
        out.write("\t\t\t\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
    return false;
  }
}
