/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2016-07-07 02:08:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.spring.model.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/triplanworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Triplan/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1463983535931L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.spring.model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/js/jquery-2.0.0.js\" ></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 검색 자동완성 스크립트 & 스타일 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("var de_area_nameArr;\r\n");
      out.write("var tempcount = 0;\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#de_area_name\").keyup(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar form_data = {\r\n");
      out.write("\t\t\t\t\t\t\tde_area_name : $(\"#de_area_name\").val(),  // 키값 : 밸류값 \r\n");
      out.write("\t\t\t\t\t\t\tis_ajax : 1004                        // 키값 : 밸류값\r\n");
      out.write("\t\t                };\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"/triplan/autoSearch.tp\",\r\n");
      out.write("\t\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\t\tdata: form_data, // \"/triplan/autoSearch.tp\" 으로 보내야할 요청 데이터값 \r\n");
      out.write("\t\t\t\tdataType: \"html\",\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\tvar resultText = data;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar resultArr = resultText.split('|'); // 리턴타입이 문자열을 가지는 배열로 리턴한다.\r\n");
      out.write("\t\t\t\t\tvar count = parseInt(resultArr[0]); // 4\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif(count > 0) {\r\n");
      out.write("\t\t\t\t\t\tde_area_nameArr = resultArr[1].split(','); // 자바 프로그래밍,자바공부,자바프로그래머 김태균,자바\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar resultHtml = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tresultHtml += \"검색어 자동완성 <br/>\";\r\n");
      out.write("\t\t\t\t\t\tfor(var i=0; i<de_area_nameArr.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\tresultHtml += \"<a href='javascript:mychoose(\\\"\" + de_area_nameArr[i] +\"\\\")'>\" + de_area_nameArr[i] + \"</a><br/>\";\r\n");
      out.write("\t\t\t\t\t\t}// end of for-------------\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#displayList\").html(resultHtml);\r\n");
      out.write("\t\t\t\t\t\t$(\"#display\").show();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\telse{ // 검색어로 시작하는 데이터가 없다라면\r\n");
      out.write("\t\t\t\t\t\t$(\"#display\").hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}// end of success-----------------\r\n");
      out.write("\t\t});// end of $.ajax()----------------------\r\n");
      out.write("\t\t\r\n");
      out.write("\t});// end of $(\"#de_area_name\").keyup()-----------\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function mychoose(title) {\r\n");
      out.write("\t$(\"#de_area_name\").val(title);\r\n");
      out.write("\t$(\"#display\").hide();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 실시간 검색어 스크립트 & 스타일 -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tappendAjax();\r\n");
      out.write("\t\t$('#display').hide();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".search\").focus(function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(this).keydown(function(event){\r\n");
      out.write("\t\t\t\tif(event.keyCode == 13)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tgoSearch();\r\n");
      out.write("\t\t\t\t\tevent.preventDefault();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goSearch()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t// 유효성 검사!\r\n");
      out.write("\t\tvar de_area_name = document.getElementById(\"de_area_name\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(de_area_name == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"검색어를 입력하세요!\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse if(de_area_name == \"경기\" || de_area_name == \"경기도\"\r\n");
      out.write("\t\t\t\t|| de_area_name == \"강원\" || de_area_name == \"강원도\"\r\n");
      out.write("\t\t\t\t|| de_area_name == \"전라\" || de_area_name == \"전라도\"\r\n");
      out.write("\t\t\t\t|| de_area_name == \"경상\" || de_area_name == \"경상도\"\r\n");
      out.write("\t\t\t\t|| de_area_name == \"충청\" || de_area_name == \"충청도\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"지역명이 정확하지 않습니다.\");\t\r\n");
      out.write("\t\t\tlocation.href=\"/triplan/main.tp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse if(de_area_name.length < 2)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"지역명이 정확하지 않습니다.\");\t\r\n");
      out.write("\t\t\tlocation.href=\"/triplan/main.tp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdocument.searchFrm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//////////////////////////////// 0702(동규) ////////////////////////////////////////\r\n");
      out.write("\t///////////// 페이징 처리 ///////////////////\r\n");
      out.write("\tvar pageNo = 0;\r\n");
      out.write("\t\r\n");
      out.write("\t// 무한 스크롤 부분 --> 스크롤이 윈도우창 맨밑에 닿았을때마다 리스트를 추가\r\n");
      out.write("  \t$(window).scroll(function(){\r\n");
      out.write("  \t\tif ($(window).scrollTop() >= $(document).height() - $(window).height()) {\r\n");
      out.write("  \t\t\taddList();\r\n");
      out.write("  \t\t}\r\n");
      out.write("  \t});\r\n");
      out.write("  \t \r\n");
      out.write("  \tfunction addList() {  \t\t\r\n");
      out.write("\t\t//1초 쉬었다가 결과물 가져오는 함수를 호출\r\n");
      out.write("\t\tif(tempcount == 0)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\ttempcount = 1;\r\n");
      out.write("\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\tappendAjax(); // div에 append할 데이터를 가져올 함수\r\n");
      out.write("\t\t\t\ttempcount = 0;\r\n");
      out.write("\t\t\t}, 1000);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("  \t\r\n");
      out.write("\r\n");
      out.write("function appendAjax() {\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t\tvar form_data = { \r\n");
      out.write("                pageNo : pageNo\r\n");
      out.write("        \t};\r\n");
      out.write("\r\n");
      out.write("\t\t // 위의 form_data를 get방식으로 dataSelldog.jsp(내용물페이지)에 보냅니다\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"GET\",\r\n");
      out.write("\t\t\turl : \"/triplan/kyu_getMainSchedule.tp\", \r\n");
      out.write("\t\t\tdata : form_data,\r\n");
      out.write("\t\t\tdataType: \"html\",      //받는 데이터방식은 html\r\n");
      out.write("\t\t\terror : function(){\r\n");
      out.write("\t\t\t\talert(\"error\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t// 성공시 id가 div_dataSelldog인 <div>태그에  dataSelldog.jsp에서 가져온 html데이터를 추가해줍니다\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\tsuccess : function(data) {\t\r\n");
      out.write("\t\t\t\t$(\"#mainSchedule\").append(data);\r\n");
      out.write("\t\t\t\tpageNo++;\t\t\t//페이지번호 증가\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//////////////////////////////// 0702(동규) ////////////////////////////////////////\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("/* \tfunction getMainSchedule()\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"/triplan/jh_getMainSchedule.tp\",\r\n");
      out.write("\t\t\ttype : \"post\",\r\n");
      out.write("\t\t\tdataType: \"html\",\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t$(\"#mainSchedule\").html(data);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\t\r\n");
      out.write("\t} */\r\n");
      out.write("\t\r\n");
      out.write("////////////////////////////////0702 동규 //////////////////////////////////\r\n");
      out.write("\tfunction viewSchedule(sc_idx)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar event = window.event;\r\n");
      out.write("\t\tvar id = event.target.id;\r\n");
      out.write("\t \tif(id == \"likebtn\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t \t\taddlike(sc_idx);\t\t// liked List에 추가, cnt + 1 와 그 반대\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tlocation.href=\"view_schedule.tp?sc_idx=\"+sc_idx;\t// 방문하며 viewcnt 증가\r\n");
      out.write("\t\t} \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction addlike(idx)\t// liked List에 추가, cnt + 1\r\n");
      out.write("\t{\t\r\n");
      out.write("\t\tvar info= { idxdata : idx };\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"/triplan/kyu_addlike.tp\",\t\t\t\r\n");
      out.write("\t\t\tdata : info,\r\n");
      out.write("\t\t\ttype : \"GET\",\r\n");
      out.write("\t\t\tdataType: \"html\",\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t$(\"#mainSchedule\").html(data);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}) // end of ajax\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("////////////////////////////////0702 동규 //////////////////////////////////\t\r\n");
      out.write("</script>\r\n");
      out.write("<style>\t\t\t/* 실검 스타일 */\r\n");
      out.write("\t#aid {text-decoration: none;}\r\n");
      out.write(" \t#searchFrm {display: inline;}\r\n");
      out.write(" \t/* #word {display: inline;} */\r\n");
      out.write(" \t/* #word {\r\n");
      out.write(" \t\theight: auto;\r\n");
      out.write(" \t} */\r\n");
      out.write(" \t#searchList {;width: 150px; height: 255px; background-color: white; position: absolute;\r\n");
      out.write(" \t\t\t\t\tborder: 1px solid green;\t\t\t \r\n");
      out.write(" \t}\r\n");
      out.write(" \t\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<div id=\"screen\">\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section id=\"main\">\r\n");
      out.write("\t\t<div class=\"search-form\">\r\n");
      out.write("\t\t\t<div class=\"container\" align=\"center\">\r\n");
      out.write("\t\t\t\t<h1>TRIPLAN</h1>\r\n");
      out.write("\t\t\t\t<form name=\"searchFrm\" action=\"/triplan/searchArea.tp\" method=\"get\">\r\n");
      out.write("\t\t\t\t<div class=\"search-box\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class=\"search\" id=\"de_area_name\" name=\"de_area_name\" size=\"30\">\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-lg btn-search\" onClick=\"goSearch();\"><span class=\"glyphicon glyphicon-search\"></span> <span class=\"span-search\"></span>검색</button>\r\n");
      out.write("\t\t\t\t\t<div id=\"display\" class=\"search2\" style=\"display:none; text-align:left\"> <!-- style=\"width:70%; border: 0px solid gray; position: relative; left:0px; top:5px; \" -->\r\n");
      out.write("\t\t\t\t\t\t<div id=\"displayList\"></div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t <!-- ///////////// 실검 ///////////// -->\r\n");
      out.write("            <div id=\"word\" style=\"margin-left:980px; margin-top:25px; font-weight: bold; font-size: 15pt; color:#ccccff\">\r\n");
      out.write("               <div id=\"realtime\" style=\"width:150%;\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "main/realtime_k.jsp", out, false);
      out.write("</div>\r\n");
      out.write("               <div id=\"searchList\" style=\"display: none;\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- ///////////// 실검 ///////////// -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t \t<div class=\"container-fluid bg-3 text-center\">    \r\n");
      out.write("\t\t\t<h3 class=\"margin\">대한민국 곳곳을 누벼 보세요</h3><br>\r\n");
      out.write("\t\t\t<div class=\"schedule-list\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"mainSchedule\" style=\"padding: 3px;\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t\r\n");
      out.write("\t<article>\r\n");
      out.write("\t</article>\r\n");
      out.write("\t\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "foot.jsp", out, false);
      out.write("\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
